### ISSUE TITLE
Volume inconstantly resets in the Pause Menu.

### ISSUE THREAD

**Issue by clinealex10** [NightAngel47/Under-the-Moonlight#7]
The volume of all groups gets reset when opening the pause menu on occasion.

### To Attempt to Reproduce:
1. Start the game or put the editor in play mode in the **Menu_Main** scene.
2. Click the **Start Game** button.
3. Hit the **Escape** key to open the **Pause Menu**.
4. Click the **Settings** button. 

### Expected behavior
The settings canvas will open with the previous volume settings with the sliders at the correct relative positions.

### Bugged behavior
The settings canvas will open with the volume settings reset, causing the volume to shoot to the max values if they were not already and the sliders to be at the max position.

### Platform:
 - Editor (Windows)

### Additional context:
This is likely an issue with either VolumeSliderBehavior.GetVolume() or VolumeManager.GetLevel(string _volumeName_, ref float _level_). VolumeSliderBehavior.GetVolume() is called for each slider when the **Settings** button is clicked and VolumeManager.GetLevel(string _volumeName_, ref float _level_) sets the variable _level_ to the stored value for the group _volumeName_. However, the bug is so inconsistent that it's difficult to test for.

**Comment by NightAngel47** [comment]
The project running in the editor affects the standalone build running on the same computer. In that, if you change the volume sliders in unity project, then the standalone's volume sliders will be set the values that the editor was left at. 

If running the project in the editor, the volume sliders will reset to max when opening the pause menu. This only happens the first time that the pause menu is opened. But happens every time when entering playmode in the editor.

**Comment by clinealex10** [comment]
This is because both the editor and the standalone build are loading the same file on the machine.

**Comment by NightAngel47** [comment]
I guess what I noticed, messing around with it more, is that the sliders are being reset to the VolumeManager.asset scriptable object's values versus pulling from the save file when the pause menu is entered. If I remove the [SerializeField] attribute from the volumes, then it consistently gets set back to 0 (or max volume).

I think I'm going to try and remove the [SerializeField] attribute from each volume float and then try and figure out why the volumes are being reset to 0 on the pause menu.

**Comment by NightAngel47** [comment]
Well it's being reset to zero because that's the default value, but figuring out why it's not loading correctly.

**Comment by NightAngel47** [comment]
Tested it on a different computer and it worked fine. I did notice that the volumes started with preset values based on the values that the volume manager scriptable object was left at when pushed. However, that's a minor thing, and this issue is fixed.
